### PR TITLE
Allow proptype check on component to accept func

### PR DESCRIPTION
**Pull request by nervetattoo**

### CODE REVIEW

**Review by krainboltgreene — APPROVED** [review]
Hell yeah!

**Comment by nervetattoo** [comment]
Great! Thanks.
Would love a bump on NPM as well so we can consume it and rid ourselves of that proptype 💩 ⚠️

**Comment by krainboltgreene** [comment]
@nervetattoo Published! (8 hours ago, haha)

**Comment by nervetattoo** [comment]
🤔I updated the package but the proptype change is not part of 2.0.3. Perhaps build script didn't run?

**Comment by krainboltgreene** [comment]
I'll check on that today. It definitely should have, my bad!

**Comment by krainboltgreene** [comment]
@nervetattoo https://github.com/ReactTraining/react-router/issues/5437#issuecomment-534796727

**Pull request merged**
